apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: retail-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: retailacr2532006019.azurecr.io/retail-api:v1
        ports:
        - containerPort: 3001