apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/teeaug27/my-argo-demo.git   # your GitHub repo
    targetRevision: main                                        # branch name
    path: helm/nginx                                            # folder where Chart.yaml lives
    helm:
      valueFiles:
        - values.yaml          
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true