apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: retail-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: retailacr2532006019.azurecr.io/retail-frontend:v1
        ports:
        - containerPort: 80